### ISSUE TITLE
Cannot translate GUI header.

### ISSUE THREAD

**Issue by workonfire** [RyanA3/TradeUI#1]
As the title says.

It is not possible to translate the GUI header in `lang.yml`.

![image](https://user-images.githubusercontent.com/34654573/79803611-96e75c80-8362-11ea-811a-e8b9d5e70e5f.png)

**Comment by RyanA3** [comment]
Thank you for your report / suggestion - This feature will be added to the lang.yml file as "menu.header" in the next tweak update
![Capture](https://user-images.githubusercontent.com/32079801/80258518-6ac52780-8651-11ea-9e39-567e45f20fd7.PNG)
