### ISSUE TITLE
TradeUI Permission

### ISSUE THREAD

**Issue by scottstorey04** [RyanA3/TradeUI#3]
Ive turned off permission requirements but it still says = <name> does not have permission to trade_ui.trade!

#HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
#         TRADE UI GENERAL CONFIG         H
#          Plugin by Felnstaren           H
#HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

# What messages do you want to see from this plugin? 
# DEBUG -> INFO -> WARN -> SEVERE
# You will see all messages above the priority you select
logger-priority: INFO

#Set to false to disable trading by using commands
allow-commands: true

#Set to false to disable trading by shift-right-clicking
allow-shifting: true

#Set to false to allow all players to trade
require-trade-permission: false

#Set to -1 to remove the distance requirement
max-trade-distance: -1

#How long until trades automatically time-out
trade-request-timeout: 100

#Set this to false to not automatically cancel requests if players walk away
cancel-request-on-walk-away: true

#Set this to true to allow players to trade with themselves, Warning: THIS IS A FEATURE PURELY FOR TESTING, the plugin WILL malfunction if you set this to true
allow-self-trading: false

#Set this to the main version your server is running on
#Supported versions
# (1.15.x)   --->   115
# (1.14.x)   --->   114
version: 115

**Comment by RyanA3** [comment]
I'll look into it, thanks for the bug report

**Comment by RyanA3** [comment]
Should be fixed now, thanks for the bug report!
